[package]
name = "visualizer"
version = "0.1.0"
authors = ["Octavia Togami <octavia.togami@gmail.com>"]
edition = "2018"

[dependencies]
nalgebra = "0.25"
supercollider = { path = ".." }
macroquad = "0.2"
