[package]
name = "visualizer"
version = "0.1.0"
authors = ["Octavia Togami <octavia.togami@gmail.com>"]
edition = "2018"

[dependencies]
nalgebra = "0.25"
num-traits = "0.2"
supercollider = { path = ".." }
raqote = "0.8"
minifb = "0.19"
